---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group the shared Nextflow submodules into one pull request
      pipeline-submodules:
        patterns:
          - "*/pipeline-Nextflow-config"
          - "*/pipeline-Nextflow-module"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
